version: '3'

services:
  sctest:
    image: golang:1.13
    container_name: sctest
    environment: 
      GOPATH: "/notgo"
    ports:
      - "9090:9090"
      - "9099:9099"
    command: ["make", "start"]
    volumes:
      - .:/go